import React from "react";

interface AIBadgeProps {
  className?: string;
}

export function AIBadge({ className = "" }: AIBadgeProps) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-sm border border-zinc-700 bg-zinc-800/60 px-1.5 py-0.5 text-[9px] font-medium uppercase tracking-wider text-zinc-500 ${className}`}
      title="This content was generated by artificial intelligence (Spear AI) for internal coaching use only."
    >
      <span className="h-1 w-1 rounded-full bg-indigo-400 shrink-0" />
      AI-generated coaching
    </span>
  );
}
